#!/bin/bash
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

clear
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e "${BLUE}---        Bienvenue à Devoxx France 2022                ---${NC}"
echo -e "${BLUE}--           Local Cassandra (Docker)                    ---${NC}"
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e ""
cd /workspace/conference-2022-devoxx/labs/

#echo -e "${GREEN}[OK]${NC} - Demarrage avec docker-compose...."
#cd /workspace/conference-2022-devoxx/labs/
#docker-compose up -d
#sleep 1
#export NOEUD1_CONTAINER_ID=`docker ps | grep dc1_seed | cut -b 1-12`
#echo -e "${GREEN}[OK]${NC} - Container id=$NOEUD1_CONTAINER_ID"
#echo -e "${GREEN}[OK]${NC} - Cassandra démarre...."
#while [ `docker container logs $NOEUD1_CONTAINER_ID | grep "Starting listening for CQL clients" | wc -l` -lt 1 ]; do
#   sleep 5
#   printf "\033[0;32m■\033[0m"
#done
#echo -e "${GREEN}[OK]${NC} - Premier noeud OK."