micronaut:
  application:
    name: lab7-micronaut
  server:
    port: 8082
    cors:
      enabled: true

cassandra:
  default:
    basic:
      session-keyspace: devoxx_micronaut
      contact-points:
        - "localhost:9042"
      load-balancing-policy:
        local-datacenter: dc1
