#!/bin/bash

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

cd /workspace/conference-2022-devoxx/labs/lab7_micronaut
mvn clean compile
clear
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e "${BLUE}- MICRONAUT [OK]                                           -${NC}"
echo -e "${BLUE}------------------------------------------------------------${NC}"

cd /workspace/conference-2022-devoxx/labs/lab7_micronaut